name: Run Python Script

on: push

env:
  api_key: ${{ secrets.API_KEY }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set PYTHONPATH
        run: export PYTHONPATH="${{ github.workspace }}"
      
      - name: Run Python Script
        run: |
          pip install requests fastapi pandas pydantic 
          python app/main.py
    