name: Run Python Script

on: push

env:
  api_key: ${{ secrets.API_KEY }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
     
      - name: Set PYTHONPATH
        run: export PYTHONPATH="${{ github.workspace }}"
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install lxml --prefer-binary
          pip install torch torchvision torchaudio
          pip install uvicorn
          pip install -r requirements.txt

      - name: Run Python Script
        run: |
          python app/main.py
    